name: rhizosphere
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::r-base=4.4.0
  - conda-forge::r-essentials
  - conda-forge::libcurl
  - conda-forge::r-curl

variables:
  PKG_CONFIG_PATH: $CONDA_PREFIX/lib/pkgconfig
  LD_LIBRARY_PATH: $CONDA_PREFIX/lib:$LD_LIBRARY_PATH