# D3 Network Panel UI
## sbp of D3 Network
sbp_d3 <- sidebarPanel(
  h4("Network Structure"),
  fluidRow(column(width = 12,
    div(class = "col-md-3",
        selectInput(inputId = "type_d3",
                    label = "Type",
                    choices = list("Taxa" = "taxa", "Samples" = "samples"),
                    selected = "taxa")),
    div(class = "col-md-3",
        selectInput(inputId = "transform_d3",
                    label = "Transform",
                    choices = c("Counts", "Prop", "RLog", "CLR"),
                    selected = "Counts")),
    div(class = "col-md-3",
        selectInput(inputId = "dist_d3",
                    label = "Distance",
                    choices = distlist,
                    selected = d3DefaultDistance)),
    div(class = "col-md-3",
        numericInputRow(inputId = "dist_d3_threshold",
                        label = "Max D",
                        value = LinkDistThreshold,
                        min = 0,
                        max = 1,
                        step = 0.025,
                        class = "col-md-12"))
  )),
  h4("Aesthetic Mapping"),
  fluidRow(column(width = 12,
    div(class = "col-md-8", uiOutput("d3_uix_node_label")),
    div(class = "col-md-4", uiOutput("d3_uix_color"))
  )),
  h4("Details"),
  fluidRow(column(width = 12,
    div(class = "col-md-4",
        numericInputRow(inputId = "d3_opacity",
                        label = "Opacity",
                        min = 0,
                        max = 1,
                        value = 1,
                        step = 0.1,
                        class = "col-md-12")),
    div(class = "col-md-4",
        numericInputRow(inputId = "d3_link_scale",
                        label = "Scale",
                        value = d3DefaultLinkScaleFactor,
                        min = 1,
                        step = 5,
                        class = "col-md-12")),
    div(class = "col-md-4",
        textInput(inputId = "d3_link_color",
                  label = "Shade",
                  value = "#666"))
  )),
  fluidRow(column(
    width = 12,
    h4("Dimensions and Download"),
    div(class = "col-md-3",
        numericInputRow(inputId = "width_d3",
                        label = "Width",
                        value = 600,
                        min = 200,
                        max = 1600,
                        step = 100,
                        class = "col-md-12")),
    div(class = "col-md-3",
        numericInputRow(inputId = "height_d3",
                        label = "Height",
                        value = 600,
                        min = 200,
                        max = 1600,
                        step = 100,
                        class = "col-md-12")),
    div(class = "col-md-2",
        div(style = "display:inline-block",
            tags$label("DL"),
            downloadButton("download_D3", " ")))
  ))
)

## D3 Network page
d3netpage <- fluidPage(
  headerPanel("Distance Threshold Network - D3"),
  sbp_d3,
  column(width = 8,
         forceNetworkOutput("D3Network")),
  fluidRow(column(width = 12, includeMarkdown("panels/paneldoc/d3Network.md")
  ))
)